server:
  port: 4433

spring:
  datasource:
    username: root
    password: Lairey2017.
    url: jdbc:mysql://127.0.0.1:3306/hall_reserve?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 10           # Redis服务器数据库
    host: 127.0.0.1   # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password: lairey2017  # Redis服务器连接密码（默认为空）
    timeout: 16000       # 连接超时时间（毫秒）
    block-when-exhausted: true
#    jedis:
#      pool:
#        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 0       # 连接池中的最小空闲连接

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity


tencent:
  xcx: # 小程序
    appId: wx58279a581c0d9f82
    appSecret: 9221b4631ce12f7d39c2cbe0c7a46489

test:
  port: 4433